"""empty message

Revision ID: 210d3cd0176c
Revises: afba5bb5cb26
Create Date: 2018-11-27 15:07:52.012513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210d3cd0176c'
down_revision = 'afba5bb5cb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_man', sa.String(length=40), nullable=True),
    sa.Column('receive_man', sa.String(length=40), nullable=True),
    sa.Column('theme', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachment', sa.String(length=50), nullable=True),
    sa.Column('add_time', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft')
    # ### end Alembic commands ###
