"""empty message

Revision ID: 23b33df95cd6
Revises: 
Create Date: 2018-11-09 18:38:23.321268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b33df95cd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('send_man', sa.String(length=40), nullable=True),
    sa.Column('theme', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachment', sa.String(length=50), nullable=True),
    sa.Column('add_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft')
    # ### end Alembic commands ###
