"""empty message

Revision ID: afba5bb5cb26
Revises: ca26c581e324
Create Date: 2018-11-12 16:36:11.793189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afba5bb5cb26'
down_revision = 'ca26c581e324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linkman', 'remark',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.drop_column('linkman', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkman', sa.Column('nickname', mysql.VARCHAR(length=40), nullable=True))
    op.alter_column('linkman', 'remark',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###
