"""empty message

Revision ID: bb1e8ccc37bf
Revises: 8a4b7dd6965c
Create Date: 2018-11-09 18:39:41.681439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb1e8ccc37bf'
down_revision = '8a4b7dd6965c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'attachment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('attachment', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
